"""Generates the Skydex app icon and notification icon.

Run from the repo root:  python tools/app-icon/generate.py
Writes the vector drawables in app/src/main/res/.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RES = os.path.join(ROOT, "app", "src", "main", "res")

# Colors. Gold matches Gold in ui/theme/Color.kt.
SKY_TOP, SKY_BOTTOM = "#2B4F86", "#121827"
GLOW = "#4A7FD0"
GOLD, GOLD_LIGHT = "#E3A72F", "#FFD978"

# ---------------------------------------------------------------- geometry
# Everything lives in the 108x108 adaptive-icon space. Launchers show the
# middle 72x72 and guarantee only a 66-wide circle, so the art stays inside it.

CX, TOP, HALF_W, SIDE = 52.0, 31.0, 20.0, 23.0
DH = HALF_W * 0.57735  # isometric 30 degrees
T = (CX, TOP)
L = (CX - HALF_W, TOP + DH)
R = (CX + HALF_W, TOP + DH)
C = (CX, TOP + 2 * DH)
BL = (L[0], L[1] + SIDE)
B = (C[0], C[1] + SIDE)
BR = (R[0], R[1] + SIDE)


def lerp(p, q, t):
    return (p[0] + (q[0] - p[0]) * t, p[1] + (q[1] - p[1]) * t)


def side_pt(start, end, u, v):
    """Point on a side face: u runs along the top edge, v goes straight down."""
    x, y = lerp(start, end, u)
    return (x, y + v)


def top_pt(p, q):
    """Point on the top face: p runs toward L, q toward R."""
    return (T[0] + (L[0] - T[0]) * p + (R[0] - T[0]) * q,
            T[1] + (L[1] - T[1]) * p + (R[1] - T[1]) * q)


def grass_lip(start, end, drips):
    """Grass edge on a side face, with Minecraft-style pixel drips."""
    n = len(drips)
    pts = [start, end]
    for i in reversed(range(n)):
        pts.append(side_pt(start, end, (i + 1) / n, drips[i]))
        pts.append(side_pt(start, end, i / n, drips[i]))
    return pts


def side_pixel(start, end, u, v, size_u=1 / 8, size_v=2.9):
    return [side_pt(start, end, u, v), side_pt(start, end, u + size_u, v),
            side_pt(start, end, u + size_u, v + size_v), side_pt(start, end, u, v + size_v)]


def top_pixel(p, q, s=1 / 8):
    return [top_pt(p, q), top_pt(p + s, q), top_pt(p + s, q + s), top_pt(p, q + s)]


def sparkle(cx, cy, r, pinch=0.14, steps=10):
    """Four-pointed star with curved sides."""
    tips = [(cx, cy - r), (cx + r, cy), (cx, cy + r), (cx - r, cy)]
    k = r * pinch
    ctrls = [(cx + k, cy - k), (cx + k, cy + k), (cx - k, cy + k), (cx - k, cy - k)]
    pts = []
    for i in range(4):
        a, c, b = tips[i], ctrls[i], tips[(i + 1) % 4]
        for s in range(steps):
            t = s / steps
            pts.append(((1 - t) ** 2 * a[0] + 2 * (1 - t) * t * c[0] + t * t * b[0],
                        (1 - t) ** 2 * a[1] + 2 * (1 - t) * t * c[1] + t * t * b[1]))
    return pts


LEFT_DRIPS = [5.5, 7.5, 5.5, 5.5, 8.5, 6, 5.5, 7]
RIGHT_DRIPS = [7, 5.5, 6, 8, 5.5, 5.5, 7.5, 5.5]

# (polygon, color) in paint order: the full-color grass block.
BLOCK = [
    ([T, R, C, L], "#7ED957"),
    ([L, C, B, BL], "#966C3F"),
    ([C, R, BR, B], "#6F4D2B"),
    (grass_lip(L, C, LEFT_DRIPS), "#5DB83F"),
    (grass_lip(C, R, RIGHT_DRIPS), "#469530"),
]
for p, q, col in [(0.25, 0.125, "#98E66F"), (0.625, 0.5, "#98E66F"), (0.125, 0.625, "#98E66F"),
                  (0.5, 0.25, "#69C447"), (0.75, 0.75, "#69C447"), (0.375, 0.75, "#98E66F")]:
    BLOCK.append((top_pixel(p, q), col))
for u, v, col in [(0.125, 11.5, "#7C5631"), (0.5, 15.9, "#AE8152"), (0.75, 11.1, "#7C5631"),
                  (0.25, 18.1, "#AE8152"), (0.625, 19.9, "#7C5631")]:
    BLOCK.append((side_pixel(L, C, u, v), col))
for u, v, col in [(0.25, 10.6, "#5A3D21"), (0.625, 14.6, "#87603A"), (0.125, 17.2, "#87603A"),
                  (0.75, 19.0, "#5A3D21"), (0.375, 19.9, "#5A3D21")]:
    BLOCK.append((side_pixel(C, R, u, v), col))

SPARKLE_BIG = sparkle(71, 30.5, 6.5)
SPARKLE_SMALL = sparkle(79.5, 45, 2.6)

STARS = [(25, 30, 1.6), (39, 20.5, 1.2), (86, 58, 1.4), (24, 70, 1.2), (82, 80, 1.6), (60, 22, 1.1), (30, 84, 1.0)]


def exploded_cube(gap=1.6):
    """Single-color cube silhouette with gaps between the faces."""
    gx, gy = gap * 0.866, gap * 0.5
    move = lambda pts, dx, dy: [(x + dx, y + dy) for x, y in pts]
    return [move([T, R, C, L], 0, -gap), move([L, C, B, BL], -gx, gy), move([C, R, BR, B], gx, gy)]


# ---------------------------------------------------------------- vectors

def path_d(pts, fmt="{:.2f}"):
    f = lambda v: fmt.format(v).rstrip("0").rstrip(".")
    return "M" + " L".join(f"{f(x)},{f(y)}" for x, y in pts) + " Z"


def transform(pts, scale, dx, dy):
    return [(x * scale + dx, y * scale + dy) for x, y in pts]


def vd(w, h, body, viewport=108, aapt=False):
    ns = ' xmlns:aapt="http://schemas.android.com/aapt"' if aapt else ""
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by tools/app-icon/generate.py. Edit that script, not this file. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{ns}\n'
            f'    android:width="{w}dp"\n    android:height="{h}dp"\n'
            f'    android:viewportWidth="{viewport}"\n    android:viewportHeight="{viewport}">\n'
            f'{body}</vector>\n')


def vd_path(pts, color):
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{path_d(pts)}" />\n'


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def write_android_vectors():
    drawable = os.path.join(RES, "drawable")
    square = [(0, 0), (108, 0), (108, 108), (0, 108)]
    bg = (f'    <path android:pathData="{path_d(square)}">\n'
          f'        <aapt:attr name="android:fillColor">\n'
          f'            <gradient android:type="linear" android:startX="54" android:startY="0"\n'
          f'                android:endX="54" android:endY="108"\n'
          f'                android:startColor="{SKY_TOP}" android:endColor="{SKY_BOTTOM}" />\n'
          f'        </aapt:attr>\n    </path>\n'
          f'    <path android:pathData="{path_d(square)}">\n'
          f'        <aapt:attr name="android:fillColor">\n'
          f'            <gradient android:type="radial" android:centerX="54" android:centerY="56"\n'
          f'                android:gradientRadius="40"\n'
          f'                android:startColor="#66{GLOW[1:]}" android:endColor="#00{GLOW[1:]}" />\n'
          f'        </aapt:attr>\n    </path>\n')
    for x, y, s in STARS:
        bg += vd_path([(x, y), (x + s, y), (x + s, y + s), (x, y + s)], "#B3FFFFFF")
    write(os.path.join(drawable, "ic_launcher_background.xml"), vd(108, 108, bg, aapt=True))

    fg = "".join(vd_path(p, c) for p, c in BLOCK)
    fg += vd_path(SPARKLE_BIG, GOLD) + vd_path(SPARKLE_SMALL, GOLD_LIGHT)
    write(os.path.join(drawable, "ic_launcher_foreground.xml"), vd(108, 108, fg))

    # Android 13+ themed icons: the launcher tints this single-color layer.
    mono = "".join(vd_path(p, "#FFFFFFFF") for p in exploded_cube())
    mono += vd_path(SPARKLE_BIG, "#FFFFFFFF") + vd_path(SPARKLE_SMALL, "#FFFFFFFF")
    write(os.path.join(drawable, "ic_launcher_monochrome.xml"), vd(108, 108, mono))

    # Status bar icon: must be white on transparent. Cube fills the 24dp box.
    scale, dx, dy = 20 / (B[1] - TOP + 3.2), 0, 0
    shapes = [transform(p, scale, 0, 0) for p in exploded_cube(1.8)]
    xs = [x for p in shapes for x, _ in p]
    ys = [y for p in shapes for _, y in p]
    dx, dy = 12 - (min(xs) + max(xs)) / 2, 12 - (min(ys) + max(ys)) / 2
    note = "".join(vd_path(transform(p, 1, dx, dy), "#FFFFFFFF") for p in shapes)
    write(os.path.join(drawable, "ic_notification.xml"), vd(24, 24, note, viewport=24))

    write(os.path.join(RES, "mipmap-anydpi", "ic_launcher.xml"), ADAPTIVE)
    write(os.path.join(RES, "mipmap-anydpi", "ic_launcher_round.xml"), ADAPTIVE)


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""


if __name__ == "__main__":
    write_android_vectors()
    print("done")
